<?xml version="1.0" encoding="utf-8"?><Database Name="mattroixanh" Class="RealDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=mattroixanh;User ID=sa" SettingsObjectName="PQT.DAC.Properties.Settings" SettingsPropertyName="mattroixanhConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TRealToCategory" Member="TRealToCategories">
    <Type Name="TRealToCategory">
      <Column Name="RealCategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RealID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TRealCategory_TRealToCategory" Member="TRealCategory" ThisKey="RealCategoryID" OtherKey="RealCategoryID" Type="TRealCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRealBaseCode" Member="TRealBaseCodes">
    <Type Name="TRealBaseCode">
      <Column Name="BaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Option1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Option2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Option3" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="TRealGroupBaseCode_TRealBaseCode" Member="TRealGroupBaseCode" ThisKey="GroupID" OtherKey="GroupID" Type="TRealGroupBaseCode" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRealCategory" Member="TRealCategories">
    <Type Name="TRealCategory">
      <Column Name="RealCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UniqueKey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="TRealCategory_TRealToCategory" Member="TRealToCategories" ThisKey="RealCategoryID" OtherKey="RealCategoryID" Type="TRealToCategory" />
    </Type>
  </Table>
  <Table Name="dbo.TRealCategoryDescription" Member="TRealCategoryDescriptions">
    <Type Name="TRealCategoryDescription">
      <Column Name="RealCategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TRealCustomer" Member="TRealCustomers">
    <Type Name="TRealCustomer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passport" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRealDescription" Member="TRealDescriptions">
    <Type Name="TRealDescription">
      <Column Name="RealID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SubContent" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRealDetail" Member="TRealDetails">
    <Type Name="TRealDetail">
      <Column Name="RealDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RealID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="File1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="File2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRealDetailDescription" Member="TRealDetailDescriptions">
    <Type Name="TRealDetailDescription">
      <Column Name="RealDetailID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SubContent" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TRealGroupBaseCode" Member="TRealGroupBaseCodes">
    <Type Name="TRealGroupBaseCode">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KeyWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TRealGroupBaseCode_TRealBaseCode" Member="TRealBaseCodes" ThisKey="GroupID" OtherKey="GroupID" Type="TRealBaseCode" />
    </Type>
  </Table>
  <Table Name="dbo.TRealImages" Member="TRealImages">
    <Type Name="TRealImage">
      <Column Name="RealID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RealImageID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TRealRoomNumber" Member="TRealRoomNumbers">
    <Type Name="TRealRoomNumber">
      <Column Name="RealID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoPhongKhach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoPhongNgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoPhongBep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoPhongWC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoPhongTho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="So1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="So2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="So3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TReal" Member="TReals">
    <Type Name="TReal">
      <Column Name="RealID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaID1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Price1" Type="System.Decimal" DbType="Decimal(15,4)" CanBeNull="true" />
      <Column Name="Price2" Type="System.Decimal" DbType="Decimal(15,4)" CanBeNull="true" />
      <Column Name="PriceText" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="XSize" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YSize" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalSize" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UseSize" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DirectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UltilityString" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ViewDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PostTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NewsType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RealProject" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="floor" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RealCode" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="WideRoad" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RealUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SizeUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>